language: pebblec
sudo: false
before_script: bash ./before_install.sh
script: make travis_build
cache:
  directories:
    - $HOME/pebble-dev
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - python2.7-dev
    - python-pip
    - python-virtualenv
env:
- PEBBLE_SDK=PebbleSDK-3.3 PEBBLE_PROJECT_PATH=stefanheule/obsidian
